---
version: 2
env:
  - CGO_ENABLED=0
builds:
  - binary: github-ci-monitor
    id: github-ci-monitor
    main: cmd/github-ci-monitor/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  - binary: github-ci-monitor-lambda
    id: github-ci-monitor-lambda
    main: cmd/github-ci-monitor-lambda/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: 'windows'
      format: 'zip'
release:
  prerelease: true
