---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GitHubCIMonitor:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: "arn:aws:serverlessrepo:ap-northeast-1:455828037039:applications/github-ci-monitor"
        SemanticVersion: 0.1.3
      Parameters:
        Config: |
          secret_id: github-ci-monitor
          region: ap-northeast-1
          repos:
          - owner: suzuki-shunsuke
            repo: github-ci-monitor
            ref: master
            check_suite: true
            tags:
              env: test
        CreateEventBridge: "true"
        EnabledEventBridge: "false"
